name: url_text
description: Url Test. Identify web links in text and make them clickable.
version: 1.0.1
homepage: https://github.com/LunaGao/Url_Text
author: LunaGao<gao.xue.qi1@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

