name: url_text
description: Url Test. Identify web links in text and make them clickable.
version: 2.0.1
homepage: https://github.com/LunaGao/Url_Text

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

